### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by nerijus** [dodo/lua-mpris#1]
I installed ldbus:

```
sudo luarocks install --server=http://rocks.moonscript.org/manifests/daurnimator ldbus DBUS_INCDIR=/usr/include/dbus-1.0/ DBUS_ARCH_INCDIR=/usr/lib64/dbus-1.0/include
```

git clone https://github.com/dodo/lua-mpris.git
Made a link ~/.config/mpv/scripts/dbus.lua pointing to mpv.lua
Tested:
$ lua dbus.lua 
lua: dbus.lua:1: module 'mpris.applet' not found:
Added

```
package.path = package.path .. ';/path/to/lua-mpris/mpv/lua-mpris/init.lua'
```

to mpv.lua. Tested again:

```
lua: error loading module 'mpris.applet' from file '/path/to/lua-mpris/mpv/lua-mpris/init.lua':
    /path/to/lua-mpris/mpv/lua-mpris/init.lua:3: too many C levels (limit is 200) in main function near '"mpris.applet"'
```

**Comment by dodo** [comment]
I added some more detail to the install instructions to the readme.

Can you please retry with that approach (try the debian way)?

**Comment by nerijus** [comment]
I use Fedora. luarocks install --local --server=http://luarocks.org/manifests/dodo lua-dbus fails:

Installing http://luarocks.org/manifests/dodo/lua-dbus-scm-0.rockspec...
Using http://luarocks.org/manifests/dodo/lua-dbus-scm-0.rockspec... switching to 'build' mode

Missing dependencies for lua-dbus:
ldbus >= scm-0

Error: Could not satisfy dependency: ldbus >= scm-0

**Comment by nerijus** [comment]
I uninstalled my earlier systemwide installed ldbus and installed everything locally:

```
luarocks install --local --server=http://rocks.moonscript.org/manifests/daurnimator ldbus DBUS_INCDIR=/usr/include/dbus-1.0/ DBUS_ARCH_INCDIR=/usr/lib64/dbus-1.0/include
luarocks install --local --server=http://luarocks.org/manifests/dodo lua-dbus
luarocks install --local --server=http://luarocks.org/manifests/dodo mpris
```

If I run mpv, it says:

```
[dbus] Lua error: /home/nerijus/.config/mpv/scripts/dbus.lua:1: module 'mpris.applet' not found:
[dbus]  no field package.preload['mpris.applet']
...
```

If I add package.path = package.path .. ';/path/to/lua-mpris/mpv/lua-mpris/init.lua' to dbus.lua : 

[dbus] Lua error: error loading module 'mpris.applet' from file /path/to/lua-mpris/mpv/lua-mpris/init.lua':
[dbus]  /path/to/lua-mpris/mpv/lua-mpris/init.lua:3: too many C levels (limit is 200) in main function near '"mpris.applet"'

**Comment by dodo** [comment]
It's easier if you change the package path with symlinks:

``` bash
ln -s /path/to/lua-mpris ~/.config/mpv/scripts/mpris
```

instead of changing `package.path`

You can install lua-dbus and ldbus this way as well:

``` bash
ln -s /path/to/lua-dbus ~/.config/mpv/scripts/lua-dbus
ln -s /path/to/ldbus/ldbus.so ~/.config/mpv/scripts/ldbus.so
```

**Comment by nerijus** [comment]
Tried that, also redid everything the debian way:

```
cd ~/.config/mpv/scripts
git clone https://github.com/dodo/lua-dbus
git clone https://github.com/dodo/lua-mpris mpris
git clone https://github.com/dodo/ldbus

cd ldbus
luarocks make --local ldbus-scm-0.rockspec LUA_INCDIR=/usr/include/lua5.2 DBUS_INCDIR=/usr/include/dbus-1.0/ DBUS_ARCH_INCDIR=/usr/lib/dbus-1.0/include
#                                                                                                    or x64: DBUS_ARCH_INCDIR=/usr/lib/x86_64-linux-gnu/dbus-1.0/include
cd ..
ln -s ldbus/ldbus.so

ln -s mpris/mpv.lua dbus.lua
```

but now mpv:

```
[dbus] 
[dbus] stack traceback:
[dbus]  [C]: in function 'require'
[dbus]  /home/nerijus/.config/mpv/scripts/lua-dbus/awesome/dbus.lua:3: in main chunk
[dbus]  [C]: in function 'require'
[dbus]  /home/nerijus/.config/mpv/scripts/lua-dbus/awesome/init.lua:5: in main chunk
[dbus]  [C]: in function 'require'
[dbus]  /home/nerijus/.config/mpv/scripts/lua-dbus/init.lua:4: in main chunk
[dbus]  [C]: in function 'require'
[dbus]  /home/nerijus/.config/mpv/scripts/mpris/applet.lua:1: in main chunk
[dbus]  [C]: in function 'require'
[dbus]  /home/nerijus/.config/mpv/scripts/dbus.lua:1: in main chunk
[dbus]  [C]: in ?
[dbus]  [C]: in ?
[dbus] Lua error: /home/nerijus/.config/mpv/scripts/lua-dbus/awesome/dbus.lua:3: module 'ldbus' not found:
[dbus]  no field package.preload['ldbus']
[dbus]  no file '/usr/share/lua/5.2/ldbus.lua'
[dbus]  no file '/usr/share/lua/5.2/ldbus/init.lua'
[dbus]  no file '/usr/lib64/lua/5.2/ldbus.lua'
[dbus]  no file '/usr/lib64/lua/5.2/ldbus/init.lua'
[dbus]  no file './ldbus.lua'
[dbus]  no file '/home/nerijus/.config/mpv/scripts/ldbus.lua'
[dbus]  no file '/usr/lib64/lua/5.2/ldbus.so'
[dbus]  no file '/usr/lib64/lua/5.2/loadall.so'
[dbus]  no file './ldbus.so'
```

**Comment by dodo** [comment]
ah, mpv doesn't extend `package.cpath`.
I added a small workaround (05b93f277a) to fix that.

Can you please retry again? :)

**Comment by nerijus** [comment]
Now mpv does not display lua errors, but I don't see mpv in kdeconnect Remote control.

**Comment by dodo** [comment]
can you find it with `d-feet`?

**Comment by nerijus** [comment]
Sorry, it's OK after I ran mpv on the PC console (before I ran it from ssh session). Thank you very much!

**Comment by dodo** [comment]
awesome! congratulations, you're the first tester (other than me) :D

**Comment by nerijus** [comment]
BTW, with the script from http://ubuntuforums.org/showthread.php?t=1059023 I was able to use mpv from ssh session with kdeconnect.
